### ISSUE TITLE
[UI/UX] Font and Footer Needs Improvements

### ISSUE THREAD

**Issue by ayushichoudhary-19** [The-Alice-In-Wonderland-Project/alicegame-2023#1]
The current font is being used for 'Apply today' and the footer is not appealing. The footer also looks very basic. The overall UI needs to be improved.

**Comment by GingerKiwi** [comment]
Thanks for the comment! 
However, you're commenting on a completely different repo. [https://alicegame.dev](https://github.com/GingerKiwi/alice2-dev-react)
Please don't add issues here.
